version: '3.8'

services:
  flask:
    build: .
    container_name: recy_flask
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    container_name: recy_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask
    restart: always